spring:
    application:
        name: poll-service
    datasource:
        url: 'jdbc:mysql://localhost:3306/poll?reconnect=true&useTimezone=true&serverTimezone=UTC'
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        username: root
    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}