spring:
    application:
        name: poll-service
    datasource:
        url: 'jdbc:mysql://localhost:3306/poll?reconnect=true&useTimezone=true&serverTimezone=UTC'
        driverClassName: com.mysql.jdbc.Driver
        password: root
        username: root
    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}

logging:
  file: logs/poll-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: ERROR
    com.sicredi.pollservice: DEBUG
    org.hibernate: ERROR

api:
    info:
        title: 'Poll Service Api'
        description: 'Poll Service Api'
        version: v1
        termOfService: 'Terms of Service'
        contact:
            name: 'Andrews Reis'
            url: null
            email: andrewsdosreis@gmail.com
        license: 'License of Api'
        licenseUrl: null