spring:
    application:
        name: poll-service
    datasource:
        url: jdbc:mysql://us-cdbr-iron-east-02.cleardb.net/heroku_3734305ebe3b61f?reconnect=true&useTimezone=true&serverTimezone=UTC
        driverClassName: com.mysql.jdbc.Driver
        password: f703c6fc
        username: b7c4fd1baa2b7b
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 3
            minimum-idle: 1
            connection-test-query: 'SELECT 1'
    jpa:
        hibernate:
            use-new-id-generator-mappings: false
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}
    rabbitmq:
        host: buck.rmq.cloudamqp.com
        port: 5672
        virtual-host: xgpesumw
        username: xgpesumw
        password: 4IOdCr2OUjb6d6asNxERxMHVhUX22MBj

rabbitmq:
    PollResult:
        exchange: PollResult.exchange

user-info:
    api: https://user-info.herokuapp.com/users/

logging:
    file: logs/poll-service.log
    pattern:
        console: "%d %-5level %logger : %msg%n"
        file: "%d %-5level [%thread] %logger : %msg%n"
    level:
        org.springframework.web: ERROR
        com.sicredi.pollservice: DEBUG
        org.hibernate: ERROR

api:
    info:
        title: 'Poll Service Api'
        description: 'Poll Service Api for Tech Challenge'
        version: v1
        termOfService: 'Terms of Service'
        contact:
            name: 'Andrews dos Reis'
            url: null
            email: andrewsdosreis@gmail.com
        license: 'License of Api'
        licenseUrl: null