spring:
    application:
        name: poll-service
    datasource:
        url: 'jdbc:mysql://localhost:3306/poll?reconnect=true&useTimezone=true&serverTimezone=UTC'
        driverClassName: com.mysql.cj.jdbc.Driver
        password: root
        username: root
        type: com.zaxxer.hikari.HikariDataSource
        hikari:
            maximum-pool-size: 10
            minimum-idle: 1
            connection-test-query: 'SELECT 1'
    jpa:
        properties:
            hibernate: {dialect: org.hibernate.dialect.MySQL5InnoDBDialect}
